###
# oh-my-zsh configs
###

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agency"
DEFAULT_USER=$USER

COMPLETION_WAITING_DOTS="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

###
# custom configs
###

if [ -f /etc/profile ]; then
  PATH=""
  source /etc/profile
fi

# use vim as visual editor
export VISUAL=vim
export EDITOR=$VISUAL

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# NVM
if [ -s ~/.nvm/nvm.sh ]; then
	NVM_DIR=~/.nvm
	source ~/.nvm/nvm.sh
fi

# paths
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="/usr/local/rbenv/bin:$PATH"

# ruby version manager
export RBENV_ROOT="/usr/local/rbenv"
eval "$(rbenv init - )"

# use overcommit on all git repos
export GIT_TEMPLATE_DIR=`overcommit --template-dir`

# ssh
 SSH_KEY_PATH="~/.ssh/dsa_id"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
