###
# oh-my-zsh configs 
###

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"
DEFAULT_USER=$USER

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh


###
# custom configs 
###

# use vim as visual editor
export VISUAL=vim
export EDITOR=$VISUAL

# aliases 
[[ -f ~/.aliases ]] && source ~/.aliases

# node version manager
export NVM_DIR="/home/vagrant/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# ruby version manager
export RBENV_ROOT="/usr/local/rbenv"
eval "$(rbenv init - --no-rehash)"

export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="./bin:$PATH"
export PATH=/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/redis/bin:/usr/local/pgsql/bin:./bin:/usr/local/abbyy/bin:$PATH

# ssh
 SSH_KEY_PATH="~/.ssh/dsa_id"
